# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from messages import tg_pb2 as messages_dot_tg__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messages/tg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TgServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Exchange = channel.stream_stream(
                '/messages.TgService/Exchange',
                request_serializer=messages_dot_tg__pb2.NewEvent.SerializeToString,
                response_deserializer=messages_dot_tg__pb2.ActionRequired.FromString,
                _registered_method=True)


class TgServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Exchange(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TgServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Exchange': grpc.stream_stream_rpc_method_handler(
                    servicer.Exchange,
                    request_deserializer=messages_dot_tg__pb2.NewEvent.FromString,
                    response_serializer=messages_dot_tg__pb2.ActionRequired.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messages.TgService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messages.TgService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TgService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Exchange(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/messages.TgService/Exchange',
            messages_dot_tg__pb2.NewEvent.SerializeToString,
            messages_dot_tg__pb2.ActionRequired.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
