# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages/tg.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'messages/tg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11messages/tg.proto\x12\x08messages\"\xf6\x02\n\x08NewEvent\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.messages.MessageType\x12\x12\n\nis_private\x18\x02 \x01(\x08\x12.\n\x06\x63onfig\x18\x03 \x03(\x0b\x32\x1e.messages.NewEvent.ConfigEntry\x12\x30\n\x07payload\x18\x04 \x03(\x0b\x32\x1f.messages.NewEvent.PayloadEntry\x12;\n\rsystem_config\x18\x05 \x03(\x0b\x32$.messages.NewEvent.SystemConfigEntry\x1a-\n\x0b\x43onfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x33\n\x11SystemConfigEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb5\x01\n\x0e\x41\x63tionRequired\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.messages.MessageType\x12\x16\n\x0erequire_answer\x18\x02 \x01(\x08\x12\x36\n\x07payload\x18\x03 \x03(\x0b\x32%.messages.ActionRequired.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*l\n\x0bMessageType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0f\n\x0bNEW_MESSAGE\x10\x01\x12\x10\n\x0c\x45\x44IT_MESSAGE\x10\x02\x12\x12\n\x0e\x44\x45LETE_MESSAGE\x10\x03\x12\x07\n\x03\x41\x43K\x10\x04\x12\x10\n\x0cSEND_REQUEST\x10\x05\x32I\n\tTgService\x12<\n\x08\x45xchange\x12\x12.messages.NewEvent\x1a\x18.messages.ActionRequired(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages.tg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEWEVENT_CONFIGENTRY']._loaded_options = None
  _globals['_NEWEVENT_CONFIGENTRY']._serialized_options = b'8\001'
  _globals['_NEWEVENT_PAYLOADENTRY']._loaded_options = None
  _globals['_NEWEVENT_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_NEWEVENT_SYSTEMCONFIGENTRY']._loaded_options = None
  _globals['_NEWEVENT_SYSTEMCONFIGENTRY']._serialized_options = b'8\001'
  _globals['_ACTIONREQUIRED_PAYLOADENTRY']._loaded_options = None
  _globals['_ACTIONREQUIRED_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGETYPE']._serialized_start=592
  _globals['_MESSAGETYPE']._serialized_end=700
  _globals['_NEWEVENT']._serialized_start=32
  _globals['_NEWEVENT']._serialized_end=406
  _globals['_NEWEVENT_CONFIGENTRY']._serialized_start=260
  _globals['_NEWEVENT_CONFIGENTRY']._serialized_end=305
  _globals['_NEWEVENT_PAYLOADENTRY']._serialized_start=307
  _globals['_NEWEVENT_PAYLOADENTRY']._serialized_end=353
  _globals['_NEWEVENT_SYSTEMCONFIGENTRY']._serialized_start=355
  _globals['_NEWEVENT_SYSTEMCONFIGENTRY']._serialized_end=406
  _globals['_ACTIONREQUIRED']._serialized_start=409
  _globals['_ACTIONREQUIRED']._serialized_end=590
  _globals['_ACTIONREQUIRED_PAYLOADENTRY']._serialized_start=307
  _globals['_ACTIONREQUIRED_PAYLOADENTRY']._serialized_end=353
  _globals['_TGSERVICE']._serialized_start=702
  _globals['_TGSERVICE']._serialized_end=775
# @@protoc_insertion_point(module_scope)
